apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: dynatrace-subscription
  namespace: dynatrace
spec:
  channel: alpha
  name: dynatrace-operator
  source: dynatrace-catalog
  sourceNamespace: dynatrace
